import Link from "next/link";

export default function HealingHeroesPage() {
  return <>
    <section className="inner-hero inner-hero-short"><div className="shell"><span className="eyebrow">Program</span><h1>Healing Heroes</h1><p className="lead">Support, education, resources, and community for veterans exploring plant-based wellness.</p><div className="actions"><a className="button" href="https://calendly.com/homegrown4heroes/new-member-consult" target="_blank" rel="noreferrer">Schedule a Call</a><Link className="button button-ghost" href="/contact">Program Signup</Link></div></div></section>
    <section className="section"><div className="shell split"><article><span className="eyebrow">Welcome veterans</span><h2>You are not on this journey alone.</h2><p>Homegrown4Heroes created Healing Heroes to help veterans find reliable information, supportive community, and access to resources centered on clean, high-quality cannabis and overall well-being.</p><p>Whether you are learning about available programs, looking for resources, or simply trying to connect with others, the organization is here to help veterans navigate the next step.</p></article><aside className="card"><span className="eyebrow">Need a medical card?</span><h3>Explore the medical card resource.</h3><p>Homegrown4Heroes works with a medical cannabis card provider to help veterans understand the process.</p><Link className="text-link" href="/programs/medical-card">Medical Card Information →</Link></aside></div></section>
    <section className="section section-soft"><div className="shell narrow"><span className="eyebrow">VA information</span><h2>Cannabis use and VA care</h2><p className="lead">The U.S. Department of Veterans Affairs states that participation in state marijuana programs does not affect eligibility for VA care and services. Veterans should discuss cannabis use with their healthcare providers as part of comprehensive care planning.</p><p className="small-copy">This page is informational and is not medical or legal advice.</p></div></section>
  </>;
}
